### ISSUE TITLE
Why this package cannot be installled from the Julia manager? 

### ISSUE THREAD

**Issue by Fishermanljh** [mkhraijah/PowerModelsADA.jl#4]
julia> Pkg.add("PowerModelsADA")
    Updating registry at `C:\Users\eee\.julia\registries\General.toml`
ERROR: The following package names could not be resolved:
 * PowerModelsADA (not found in project, manifest or registry)
   Suggestions: PowerModelsACDC PowerModelsSecurityConstrained PowerModelsAnnex PowerModelsAnalytics PowerModelsStability PowerModelsInterfaceStacktrace:

**Comment by mkhraijah** [comment]
We are still working on minor details before adding the package to the Julia package manager. On the meanwhile, you can download the source code and use `include("package_path/src/PowerModelsADA.jl")` to use the package.

**Comment by Fishermanljh** [comment]
Got it. Many thanks for your reply and help.

**Comment by Fishermanljh** [comment]
Sorry to bother you again, since I am a new comer to Julia.  While installing the package on VScode in Windows, I met the following question (for the dependent package:  KaHyPar ). I have no idea what is going on, could you please give me some hints on this. Many and many thanks for your help.

Precompiling project...
  ✗ KaHyPar
  0 dependencies successfully precompiled in 1 seconds. 10 already precompiled.
  1 dependency errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the package
     Testing Running tests...
ERROR: LoadError: UndefVarError: libkahypar not defined

**Comment by mkhraijah** [comment]
> Sorry to bother you again, since I am a new comer to Julia. While installing the package on VScode in Windows, I met the following question (for the dependent package: KaHyPar ). I have no idea what is going on, could you please give me some hints on this. Many and many thanks for your help.
> 
> Precompiling project... ✗ KaHyPar 0 dependencies successfully precompiled in 1 seconds. 10 already precompiled. 1 dependency errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the package Testing Running tests... ERROR: LoadError: UndefVarError: libkahypar not defined

I'm not sure what is the cause of this error. Try to install KaHyPar manually using `]add KaHyPar`, and then reinstall the package again.

**Comment by mkhraijah** [comment]
> Many thanks for your great help. Since I am using the Windows system, I wonder whether this package is built on the Windows or Linux ?

We built the package on Linux, but I think it should work well with Windows.

**Comment by Fishermanljh** [comment]
Got it.  Since KaHyPar does not support Windows well, the problem emerges when compiling this package. I might figure out a way of this how to implement it on Windows.

**Comment by Fishermanljh** [comment]
Many thanks for your help. I managed to run this package on Linux.

**Comment by mkhraijah** [comment]
I'm glad that you managed to run the package. It appears there is an issue with the c++ KaHyPar package on Windows. I will contact the authors and see if they are going to fix it.
